#Northern Line stations
BFSTC="Belfast Central"
LBURN="Lisburn"
LURGN="Lurgan"
PDOWN="Portadown"
PPASS="Poyntzpass"
NEWRY="Newry"
DDALK="Dundalk"
DGHDA="Drogheda"
MSNEY="Mosney"
BBRGN="Balbriggan"
SKRES="Skerries"
MHIDE="Malahide"
PMNCK="Portmarnock"
HWTHJ="Howth Junction"
KBRCK="Kilbarrack"
RAHNY="Raheny"
HTOWN="Harmonstown"
KLSTR="Killester"
CTARF="Clontarf Road"
CNLLY="Dublin Connolly"
#Rosslare Line stations
